
"""
Qwen Client
-----------

Local Qwen GGUF inference using llama-cpp-python.

The model answers ONLY from the supplied portfolio context.
"""

from pathlib import Path
from typing import Optional

from llama_cpp import Llama


# =============================================================================
# PATHS
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

MODEL_PATH = (
    PROJECT_ROOT
    / "models"
    / "qwen2.5-0.5b-instruct.gguf"
)


# =============================================================================
# CONFIG
# =============================================================================

N_CTX = 4096

MAX_TOKENS = 180

TEMPERATURE = 0.1

TOP_P = 0.9

REPEAT_PENALTY = 1.35

FREQUENCY_PENALTY = 0.6


# =============================================================================
# CLIENT
# =============================================================================

class QwenClient:

    def __init__(
        self,
        model_path: Optional[Path] = None,
    ):

        self.model_path = (
            Path(model_path)
            if model_path
            else MODEL_PATH
        )

        # ---------------------------------------------------------------------
        # Check model
        # ---------------------------------------------------------------------

        if not self.model_path.exists():

            raise FileNotFoundError(
                "\nQwen model not found.\n"
                f"Expected path:\n"
                f"{self.model_path}\n\n"
                "Download the GGUF model and place it inside:\n"
                f"{PROJECT_ROOT / 'models'}"
            )

        print("-> Loading Qwen model...")
        print(
            f"  Model: "
            f"{self.model_path.name}"
        )

        # ---------------------------------------------------------------------
        # Load model
        # ---------------------------------------------------------------------

        import gc
        gc.collect()

        self.llm = Llama(
            model_path=str(self.model_path),
            n_ctx=N_CTX,
            n_batch=128,
            logits_all=False,
            verbose=False,
        )

        print("[OK] Qwen model loaded")

    # =========================================================================
    # PROMPT
    # =========================================================================

    @staticmethod
    def build_prompt(
        question: str,
        context: str,
    ) -> str:
        """
        Build a clear, explicit RAG prompt for Qwen 0.5B.
        Context comes BEFORE Question for better attention focus.
        """

        return f"""<|im_start|>system
You are a helpful portfolio assistant for Md. Asaduzzaman Shuvo.
Answer the user's question accurately using ONLY the facts provided in the Context below.
- State facts clearly and directly.
- Do NOT repeat any list items or sentences.
- Never invent details or dates.
- Do NOT guess URLs, dates, or statistics. Only state what appears in the context.
- If a project or paper title is given, use the exact title from the context.
- Do NOT add explanations or elaborations beyond what the context states.
- Keep your response concise (3-5 items or sentences maximum).
- If the context does not contain relevant information, state that the information is not available in the portfolio data.
<|im_end|>
<|im_start|>user
Context:
{context}

Question: {question}
<|im_end|>
<|im_start|>assistant
""".strip()

    # =========================================================================
    # GENERATE
    # =========================================================================

    def generate(
        self,
        question: str,
        context: str,
    ) -> str:

        prompt = self.build_prompt(
            question=question,
            context=context,
        )

        output = self.llm(
            prompt,
            max_tokens=MAX_TOKENS,
            temperature=TEMPERATURE,
            top_p=TOP_P,
            repeat_penalty=REPEAT_PENALTY,
            frequency_penalty=FREQUENCY_PENALTY,
            stop=[
                "<|im_end|>",
                "<|im_start|>",
            ],
        )

        try:

            answer = (
                output["choices"][0]["text"]
            )

        except Exception:

            return (
                "The available portfolio data does not contain that information."
            )

        answer = answer.strip()

        # Remove leading colon or "Answer:" prefix if generated by LLM
        while answer.startswith(":") or answer.startswith("-"):
            answer = answer[1:].strip()

        if answer.startswith("Answer:"):
            answer = answer[7:].strip()

        # Clean trailing prompt leakage phrases if LLM appended it
        leakage_phrases = [
            "The available portfolio data does not contain that information.",
            "the information is not available in the portfolio data",
        ]
        for phrase in leakage_phrases:
            if answer.startswith(phrase):
                return phrase
            if phrase in answer:
                answer = answer.replace(phrase, "").strip()

        # Strip hallucinated URL placeholders like "(Link)" or "(Link to GitHub)"
        import re
        answer = re.sub(
            r'\s*\(Link[^)]*\)',
            '',
            answer,
        )

        # Strip trailing incomplete sentences (cut off mid-word)
        if answer and not answer[-1] in '.!?:)"\'':
            last_sentence_end = max(
                answer.rfind('. '),
                answer.rfind('? '),
                answer.rfind('! '),
                answer.rfind('.\n'),
                answer.rfind('?\n'),
                answer.rfind('!\n'),
            )
            if last_sentence_end > len(answer) * 0.5:
                answer = answer[:last_sentence_end + 1]

        if not answer:

            return (
                "The available portfolio data does not contain that information."
            )

        return answer


# =============================================================================
# SINGLETON
# =============================================================================

_client = None


def get_qwen_client():

    global _client

    if _client is None:

        _client = QwenClient()

    return _client


# =============================================================================
# PUBLIC FUNCTION
# =============================================================================

def generate_answer(
    question: str,
    context: str,
) -> str:

    client = get_qwen_client()

    return client.generate(
        question=question,
        context=context,
    )


# =============================================================================
# TEST
# =============================================================================

def main():

    print("=" * 70)
    print("QWEN CLIENT TEST")
    print("=" * 70)

    question = "Tell me about Shuvo"

    context = """
PORTFOLIO KNOWLEDGE BASE

[Document 1]
Document: AI_resume_shuvo.pdf
Page: 1

Md. Asaduzzaman Shuvo
AI Engineer · Machine Learning

AI researcher and engineer specializing in LLMs,
low-resource NLP, multimodal AI, and computer vision.

Author of 2 published papers and 3 papers under review.

Skills include PyTorch, Hugging Face, QLoRA/LoRA,
LangChain, YOLO, and FastAPI.

Solved 260+ problems across LeetCode,
Codeforces, and other competitive programming platforms.
"""

    print()
    print(f"Question:\n{question}")

    print()
    print("→ Generating answer...")

    answer = generate_answer(
        question=question,
        context=context,
    )

    print()
    print("-" * 70)
    print("QWEN ANSWER")
    print("-" * 70)
    print(answer)


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    main()
